name: Docker image build and push

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:      

            
jobs:
    build:
        runs-on: ubuntu-latest
        environment: DEV
        
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
            
            - name: setup docker build
              uses: docker/setup-buildx-action@v2
              
            - name: Login to docker
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                    context: .
                    push: true
                    tags: |
                        ${{secrets.DOCKER_USERNAME}}/backend-ai-bg-remover:${{ github.sha }}
                        ${{secrets.DOCKER_USERNAME}}/backend-ai-bg-remover:latest  
        
            - name: Logout from Docker Hub
              run: docker logout