name: Auto Increment Tag and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Bump version
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        with:
          github_token: ${{ secrets.GHUB_TOKEN }}
          default_bump: patch
          tag_prefix: "v"
          push_to_branch: main

      - name: Build application
        run: npm run build

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          body: |
            ## Changes
            - Automated release with incremented version.
          draft: false
          prerelease: false
          token: ${{ secrets.GHUB_TOKEN }}
